apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nav-epj-auth-server
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: {{port}}
  ingresses:
    - {{ingress}}
  liveness:
    path: /internal/actuator/liveness
  readiness:
    path: /internal/actuator/readiness
  startup:
    path: /internal/actuator/health
    initialDelay: 30
  accessPolicy:
    inbound:
      rules:
        - application: nav-fhir-server
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
