apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nav-epj-auth-server
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: /monitoring/health/liveness
    delay: 120
  readiness:
    delay: 120
    path: /monitoring/health/readiness
    initialDelay: 30
  accessPolicy:
    inbound:
      rules:
        - application: nav-fhir-server
        - application: nav-epj-auth-server
    outbound:
      external:
        - host: helseid-sts.test.nhn.no
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  envFrom:
    - secret: epj-auth-secrets