management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitoring

spring:
  main:
    banner-mode: off
  application:
    name: nav-epj-auth-server
  security:
    oauth2:
      client:
        registration:
          nav-epj-auth-server:
            provider: helse-id
            client-id: "14c1f2b2-885c-42b8-87c4-3ea5ab2e9ac3"
            client-authentication-method: "private_key_jwt"
            authorization-grant-type: "authorization_code"
            scope:
              - "openid"
              - "profile"
              - "helseid://scopes/identity/pid"
              - "helseid://scopes/identity/security_level"
            redirect-uri: "${server.base-url}/login/oauth2/code/nav-epj-auth-server"
            client-name: "NAV EPJ Auth Server"
        provider:
          helse-id:
            authorization-uri: "https://helseid-sts.test.nhn.no/connect/authorize"
            token-uri: "https://helseid-sts.test.nhn.no/connect/token"
            user-info-uri: "https://helseid-sts.test.nhn.no/userinfo"
            # user-name-attribute: "sub"
            jwk-set-uri: "https://helseid-sts.test.nhn.no/.well-known/openid-configuration/jwks"
      authorizationserver:
        client:
          nav-epj:
            registration:
              client-id: "nav-epj"
              client-authentication-methods:
                - "private_key_jwt"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://localhost:3005/oauth2/callback"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: false
            require-proof-key: true
            token-endpoint-authentication-signing-algorithm: "RS256"
            # jwk-set-uri: TODO what is?
          syk-inn:
            registration:
              client-id: "syk-inn"
              client-authentication-methods:
                - "private_key_jwt"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:3000/fhir/"
                - "https://syk-inn.ekstern.dev.nav.no/fhir"
              scopes:
                - "openid"
                - "profile"
                - "fhirUser"
                - "launch"
                - "patient/*.read"
                - "user/*.read"
                - "offline_access"
            require-authorization-consent: false
            require-proof-key: true
            token-endpoint-authentication-signing-algorithm: "RS256"
          nav-smart-on-fhir-example:
            registration:
              client-id: "NAV_SMART_on_FHIR_example"
              client-authentication-methods:
                - "private_key_jwt"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:5173/"
                - "https://nav-on-fhir.ekstern.dev.nav.no/"
              scopes:
                - "openid"
                - "profile"
                - "fhirUser"
                - "launch"
                - "patient/*.*"
                - "user/*.*"
                - "offline_access"
            require-authorization-consent: true
            require-proof-key: true
            token-endpoint-authentication-signing-algorithm: "RS256"