management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitoring

spring:
  main:
    banner-mode: off
  application:
    name: nav-epj-auth-server
  security:
    oauth2:
      client:
        registration:
          nav-epj-auth-server: # Matches the name of this application
            provider: helse-id
            client-id: "14c1f2b2-885c-42b8-87c4-3ea5ab2e9ac3"
            client-authentication-method: "private_key_jwt"
            authorization-grant-type: "authorization_code"
            scope:
              - "openid"
              - "profile"
              - "helseid://scopes/identity/pid"
              - "helseid://scopes/identity/security_level"
            redirect-uri: "${server.base-url}/login/oauth2/code/${spring.application.name}"
        provider:
          helse-id:
            authorization-uri: ${helseid.base-url}/connect/authorize
            token-uri: ${helseid.base-url}/connect/token
            user-info-uri: ${helseid.base-url}/userinfo
            user-name-attribute: "sub"
            jwk-set-uri: ${helseid.base-url}/.well-known/openid-configuration/jwks
      authorizationserver:
        client:
          syk-inn:
            registration:
              client-id: "syk-inn"
              client-authentication-methods:
                - "private_key_jwt"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:3000/fhir/"
                - "https://syk-inn.ekstern.dev.nav.no/fhir"
              scopes:
                - "openid"
                - "profile"
                - "fhirUser"
                - "launch"
                - "patient/*.read"
                - "user/*.read"
                - "offline_access"
            require-authorization-consent: false
            require-proof-key: true
            token-endpoint-authentication-signing-algorithm: "RS256"
          nav-smart-on-fhir-example:
            registration:
              client-id: "NAV_SMART_on_FHIR_example"
              client-authentication-methods:
                - "private_key_jwt"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:5173/"
                - "https://nav-on-fhir.ekstern.dev.nav.no/"
              scopes:
                - "openid"
                - "profile"
                - "fhirUser"
                - "launch"
                - "patient/*.*"
                - "user/*.*"
                - "offline_access"
            require-authorization-consent: true
            require-proof-key: true
            token-endpoint-authentication-signing-algorithm: "RS256"

helseid:
  base-url: ${helseid.base-url}
  openid:
    jwk: ${helseid.openid.jwk}